README.md, examples/exampleUtils.py, examples/runAssembleTask.py, examples/runIsrTask.py, python/lsst/__init__.py, python/lsst/ip/__init__.py, python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isr.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py, tests/testBiasAndDarkCorrection.py, tests/testBrighterFatter.py, tests/testFlatAndIlluminationCorrection.py, tests/testFringes.py, tests/testLinearizeLookupTable.py, tests/testLinearizeSquared.py, tests/testOverscanCorrection.py, tests/testSaturationCorrection.py
=> DM-7296: Port to python 3

python/lsst/ip/isr/isrTask.py, tests/test_setValidPolygonIntersect.py
and update for Detector.getCenter returning a Point2D
instead of a CameraPoint
=> DM-12447: Remove TransformMap.transform, Camera.transform and Detector.transform

python/lsst/ip/isr/measureCrosstalk.py
Small refactor of MeasureCrosstalkTask to move the calculations to a run method.
=> DM-15311: {{Refactor MeasureCrosstalkTask.runDataRef to new run.}}

tests/test_flatAndIlluminationCorrection.py
=> DM-22728: Handle immutable amplifiers in test suite.

python/lsst/ip/isr/isrTask.py
Check linearity with doLinearize method in gen3.
=> DM-22680: linearizer attempts to run in gen3 when LinearizerType=None

python/lsst/ip/isr/overscan.py
Mask saturated overscan pixels before fitting.
=> DM-25149: Fix w18 ISR regression

python/lsst/ip/isr/isrTask.py
Also fix docstrings to reflect actual return type.
=> DM-25776: Adapt to daf_butler API changes in crosstalk lookup.

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/crosstalk.py
Fix errors discovered by ci_cpp.
=> DM-23302: Add ci_cpp package to allow calibration product generation to be tested

python/lsst/ip/isr/ptcDataset.py, tests/test_ptcDataset.py
This reverts commit e5a6656a818edc2a397f4f0dc5762f7b7759bd3a, reversing
changes made to 763706fb4105b60042e8d79667467657e813f7ce.
=> DM-23159-revert: Revert "Merge branch 'tickets/DM-23159' into master"

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py, tests/test_linearize.py
Add linearizer connection for gen3.
=> DM-23985: Cannot do linearity corrections in Gen 3 DECam processing

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrTask.py, tests/test_crosstalk.py
Improve inter-chip crosstalk application so it works.
=> DM-27833: Enable gen3 inter-chip crosstalk for DECam

python/lsst/ip/isr/fringe.py
Prevent the fringe mask plane being added into the output image.
=> DM-27612: Applying fringe correction adds numerous mask features

python/lsst/ip/isr/brighterFatterKernel.py
Improve level = DETECTOR brighter-fatter kernels:
* Fix incorrect super().__init__() call
* Fix handling of initFromCamera
* Switch to lowercase calib name
* Fix handling for DETECTOR models not having amp-level products
* Only persist amp-level products if level == AMP
=> DM-30351: Make sure brighter-fatter correction is working on DC2 data for DP0.2

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py
This is mostly a simple warn->warning change but there are a couple of places where an f-string was being used in a format message.
=> DM-31060: Minor cleanups of logging

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/linearize.py, python/lsst/ip/isr/photodiodeCorrection.py, tests/test_linearize.py, tests/test_photodiodeCorrection.py
This ticket was to add the photodiode and photodiode systematic correction code to the linearizer.
=> DM-33297: Add correction of systematic photodiode error

python/lsst/ip/isr/isrTask.py
Discard the correct input for fringes.
=> DM-34481: Fix cp_pipe fringe PipelineDataCycleError

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/deferredCharge.py, python/lsst/ip/isr/isrStatistics.py, python/lsst/ip/isr/isrTask.py, tests/test_deferredCharge.py
This change adds the deferred charge calibration type, the serial trap class, and the correction task to repair CTI issues.  An additional task to handle the calculation of statistics during ISR is also new.
=> DM-33138: Add CTI correction to ip_isr

python/lsst/ip/isr/overscan.py
=> DM-36163: Remove unnecessary ISR log messages

python/lsst/ip/isr/deferredCharge.py
Fix handling of NaN padding in serial trap coefficients.
This version properly truncates the padded values, and filters incoming NaN values from the trap coefficients on construction.
=> DM-36260: Deferred charge trap array contains NaNs, butler access fails

python/lsst/ip/isr/overscan.py, tests/test_overscanCorrection.py
If too many pixels (default is more than 10% of all pixels) are masked, we don't make the parallel overscan correction
=> DM-36068: Parallel overscan correction seems to cause failures in PTC

python/lsst/ip/isr/isrTask.py
Fix typos preventing CTI from running.
=> DM-36280: Fix incorrect dataset type for CTI dataset in IsrTask

python/lsst/ip/isr/brighterFatterKernel.py
Change log message to info level.
=> DM-36596: Change brighter-fatter warning to info level log.

python/lsst/ip/isr/isrTask.py
Add calibration provenance header info.
=> DM-37129: Store list of calibrations used in output header

python/lsst/ip/isr/isrTask.py
Add used GAIN/RN values to exposure header/metadata.
=> DM-33464: Update headers in postISRCCD

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/isrTask.py, tests/test_calibType.py
Add new IsrCalib method to handle sequencer checks.
=> DM-36390: calibrations should track sequencer crc

python/lsst/ip/isr/brighterFatterKernel.py, python/lsst/ip/isr/isrTask.py
Fix incorrect BF kernel transposes.
=> DM-38827: Possible inconsistency in indexing in the brighter fatter kernel generation/correction

python/lsst/ip/isr/isrTask.py, tests/test_isrTask.py
Add method for ip_isr to produce binned images.
=> DM-40520: Add support for binning images to ip_isr

python/lsst/ip/isr/brighterFatterKernel.py
Demote log message to debug level.
=> DM-41791:  Demote bfk version message to debug

python/lsst/ip/isr/isrTaskLSST.py
Update order of ISR steps in the LSST ISR task.
=> DM-42459: ISR boxes version 2.0

python/lsst/ip/isr/isrStatistics.py
This adds 
* bias shift calculation
* amp correlation calculation
=> DM-42159:  eo_pipe/cp_verify parity: bias

python/lsst/ip/isr/defects.py, python/lsst/ip/isr/isrStatistics.py
Add defect calibration handler for hot/cold pixels, bad columns.
Add isrStatistics handler to pass these quantities.
=> DM-42161: eo_pipe/cp_verify parity: defects

tests/test_variance_plane.py
I have moved the unit test from `meas_algorithms` to this repository to avoid circular dependencies.
=> DM-32355: Develop function and unit test to remove Poisson contribution from sources in variance plane

python/lsst/ip/isr/isrTaskLSST.py
This PR should update isrTaskLSST with all the relevant changes done to isrTask since last year. I might have missed important updates or made unnecessary updates, let me know if this is the case. 
Jenkins is currently running.
=> DM-40903: upstream changes of isrTask to isrTaskLSST

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/isrTaskLSST.py, tests/test_defect.py, tests/test_isrFunctions.py
See this ticket --> https://rubinobs.atlassian.net/browse/DM-44305
=> DM-44305: Implement Gaussian Process interpolation over bad pixels

python/lsst/ip/isr/isrFunctions.py
See here: https://rubinobs.atlassian.net/browse/DM-46710
=> DM-46710: Disable jax in Gaussian process interp

python/lsst/ip/isr/isrTaskLSST.py, tests/test_isrTaskLSST.py
=> DM-48878: Set parallelOverscans=None default in IsrTaskLSST

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTaskLSST.py, tests/test_isrFunctions.py, tests/test_isrTaskLSST.py
The code is linted and passes through ISR tests successfully but the jenkins run failed, I need to look at why.
=> DM-47681: ITL edge bleed masking

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/photodiode.py
The main blockers on this is now how reliable the blocks/scheduler/etc are at generating GROUPID values.  I think this is ready for review, with the intent that we'll run this manually until we know what that reliability is.
=> DM-44113: Test and update electrometer ingest for FITS files as currently written.
