python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/isrTask.py
Directly invoke afwDisplay in AssembleCcdTask and IsrTask rather than relying
on the pipe_base framework.
=> Adapt to removal of pipe.base.task.Task.display().

python/lsst/ip/isr/isrTask.py, tests/testBrighterFatter.py
This implements the brighter fatter correction method from HSC.
We generated a kernel from flat field images that
can be applied iteratively to an image to correct for intensity
dependent PSFs.  We still need to investigate when to stop iterating,
but the current settings seem to work for HSC.
This change does not include the code to generate the kernel or test the algorithm.
=> Add brighter fatter correction from obs_subaru as calibration option.

include/lsst/ip/isr.h, python/lsst/ip/isr/isrLib.i, src/Isr.cc
Makes the following replacements:
- boost::scoped_ptr -> std::unique_ptr
- boost::shared_ptr -> std::shared_ptr
- boost::weak_ptr -> std::weak_ptr
- boost::static_pointer_cast -> std::static_pointer_cast
- boost::dynamic_pointer_cast -> std::dynamic_pointer_cast
- boost::const_pointer_cast -> std::const_pointer_cast
- boost::reinterpret_pointer_cast -> std::reinterpret_pointer_cast
- boost::enamble_shared_from_this -> std::enable_shared_from_this
- boost pointer related includes -> standard library memory
=> DM-5879 Remove use of Boost smart pointers throughout the Science Pipelines

examples/exampleUtils.py, python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/isrTask.py
Update all code that used exposure time or date in Calib,
switching to VisitInfo instead.
=> Update for exposure time and date not in Calib

python/lsst/ip/isr/isrTask.py, tests/testBiasAndDarkCorrection.py
Scaling by a non-finite darktime can destroy the image.
This is important because the darktime defaults to NAN
unless set explicitly by the obs package.
=> IsrTask: check for non-finite darktime

python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isr.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py
Standardizing on python 3 division, as per the style guide. Needed because the pybind11 wrappers for objects used in this file implement `__truediv__` but not `__div__`.
=> DM-8461: Wrap pipe_tasks with pybind11

python/lsst/ip/isr/isrTask.py
There are times that one wishes to label saturated pixels but not
interpolate over them. Added config parameter indicating whether or
not to do the interpolation; by default, will do it.
=> DM-11267: IsrTask: make saturation interpolation configurable

python/lsst/ip/isr/fringe.py
Before merging DM-13260, I went and moved some code around without
testing. It turns out this broke the new test. Fixed by refactoring
common code and adding a new check.
=> DM-13408: fringe: fix test failure

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py
We don't care, and they clutter the output.
=> DM-11776: suppress numpy NAN warnings

python/lsst/ip/isr/measureCrosstalk.py, tests/test_crosstalk.py
Rename methods according to RFC-352.
Fifteen total repositories with changes.
=> DM-2639: {{Standardize primary method names, run/runDataRef, across PipeTasks}}

python/lsst/ip/isr/isrTask.py
bfKernelNew is a temporary name for this dataset
while the crossover between old and new is handled
This is largely irrelevant though, as this code has
never fired before, as only obs_subaru actually
brighter-fatter correction, and it has its own isr
task. This will be updated once this dataset is
renamed.
=> Add support for the new brighter-fatter kernels

python/lsst/ip/isr/isrTask.py
For LSST chips with 16 amps each, things that are done
per-amp quickly clutter the output, so all per-amp logs
are now at the DEBUG level except when skipping the
overscan correction, as I think this should rarely/never
happen (not when not selected, but when the bbox doesn't
overlap the CCD area).
=> Lower logger messages from INFO to DEBUG level

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py, tests/test_addDistortionModel.py
Additional configuration options now exist to define the required
input/output dataset types, and appropriate handlers correctly remove
these datasets if the isr configuration will not require (for inputs)
or generate (for outputs) those products.  As the camera configuration
is not currently fully populated, the obs_subaru/hsc configuration is
read to set the correct parameters.
=> Convert isrTask to valid pipelineTask.

python/lsst/ip/isr/isrTask.py
The inputTypeDict and outputTypeDict are constructed with all possible
input and output datasets, and are culled based on the configuration
parameters.  If the entry does not exist in the dict (possibly due to
other configurations), this can cause a KeyError.  Resolve this by
using dict.pop("key", None) instead of del dict["key"].
=> DM-17912 Fix potential KeyError in gen3 datasets.

python/lsst/ip/isr/isrTask.py
Previously the wrong config option was checked. A simple
fix without making the docs very explicit would be confusing
so now the docstrings for each option are very clear indeed.
=> tickets/DM-18065 Fix bug so that behaviour is consisten with config options

python/lsst/ip/isr/isrTask.py
For gen2 ISR, move handling of new style (cp_pipe) and old style
(numpy.ndarray) brighter-fatter kernels entirely into
IsrTask.readIsrData() method.  Based on the configuration, this should
attempt to find the appropriate style, and optionally pull the kernel
for the detector to process.  Internally, the kernel is still passed
as the single numpy.ndarray needed for the processing.
=> DM-18552: Allow use of new and old brighter-fatter kernels.

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrTask.py
In addition to the length error, this ticket also includes crosstalk correction in ip_isr to not subtract background levels calculating the corrected pixels, but to include that background when calculating the mask of significant CT pixels.
=> DM-18703 constructFlat.py --config isr.doCrosstalkBeforeAssemble=False raises a LengthError exception

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/straylight.py
...at least in Gen2.  In Gen3 (which doesn't do stray light correction yet for other reasons), we'll have custom Formatters instead.
=> DM-19393: Delegate to StrayLightTask subclasses to load their data.

bin.src/runIsr.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrMock.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/straylight.py, tests/test_assembleCcd.py, tests/test_brighterFatter.py, tests/test_crosstalk.py, tests/test_fringes.py, tests/test_isrFunctions.py, tests/test_isrMisc.py, tests/test_isrMock.py, tests/test_isrQa.py, tests/test_isrTask.py, tests/test_linearizeLookupTable.py, tests/test_measureCrosstalk.py, tests/test_saturationCorrection.py
These tests have finally converged with the addition of the `ip_isr/isrMock.py` code to supply "realistic" simulated data to check.  Running these tests uncovered some bugs in the ISR code, which has now been corrected.
The code coverage is now much better than previously, with the only major untested code being in the methods to support Gen3 butler/processing.
=> DM-15683: Add tests for ip_isr/isrTask

tests/test_assembleCcd.py, tests/test_isrFunctions.py, tests/test_isrMisc.py, tests/test_isrMock.py, tests/test_isrQa.py, tests/test_isrTask.py, tests/test_measureCrosstalk.py
The new unit tests introduced in DM-15683 did not ensure that lsst.utils.tests.init() was called.  This ticket fixes that.
=> DM-19717: Add setup_module to ensure memory tests are run.

python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isrMock.py, tests/test_fringes.py, tests/test_isrTask.py
Adding multi-component fringes to the mocks allows full tests to confirm
FringeTask handles these fits.  Return fringe solution and RMS values
for validation of the measured values.
=> DM-4441: Update isrMock for multi-component fringes.

python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py
Clarify ISR log messages, comments, and docstrings.
Change isrFunctions.brighterFatterCorrection to return final
difference and iteration count, so an old log message can be restored.
Remove old out-of-date documentation that was causing build warnings.
=> DM-20109: Improve ip_isr log messages to be more explicit

python/lsst/ip/isr/isrTask.py
Move BAD pixel value setting before interpolation.
With interpolation on, these pixels are interpolated, which means they
do not receive the image median value.  This may skew the
interpolation.
Fix interpolation exposure choice bug.
=> DM-20112: ip_isr is not handling BAD pixels as expected

python/lsst/ip/isr/isrTask.py
This abstractmethod has been removed from the base PipelineTask class as unnecessary.
=> DM-19988: Remove unnecessary getPerDatasetTypeDimensions override.

python/lsst/ip/isr/isrTask.py
The edges of amplifiers that have had the brighter-fatter correction
applied may not have had the appropriate correction applied.  To
reflect this fact, ensure that the number of edge pixels masked is the
larger of IsrTask.config.numEdgeSuspect and the brighter-fatter kernel
size.
=> DM-5081: Mark amplifier edges SUSPECT if brighter-fatter is applied.

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrMock.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/measureCrosstalk.py, tests/test_crosstalk.py, tests/test_measureCrosstalk.py
Crosstalk application currently demands that the exposure detector have the crosstalk coefficient data included in the detector definition.  This makes measuring CT on new detectors challenging, and is explicitly not used for the most well-tested cameras (HSC/DECam).  This change allows the crosstalk coefficients to be set in the isr.crosstalk configuration.
To support this change, MeasureCrosstalkTask grabbed previously isolated functions into the task class, and additional debug visualization methods were added to help assess the measurement quality.
=> DM-19214: ip_isr crosstalk shouldn't depend on detector hasCrosstalk( )and getCrosstalk()

python/lsst/ip/isr/isrTask.py
Add IsrTaskConnections to handle Gen3 API interface, moving that content out of the IsrTaskConfig class.  Miscellaneous tweaks to fix run errors and to convert to new objects and names.  This should also add the preInterpExposure output to the valid outputs for Gen3.
=> DM-20692: Update IsrTask to new Gen3 API.

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrMock.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py, tests/test_crosstalk.py, tests/test_empiricalVariance.py, tests/test_flatAndIlluminationCorrection.py, tests/test_isrFunctions.py, tests/test_isrTask.py, tests/test_linearizeLookupTable.py, tests/test_linearizeSquared.py, tests/test_suspectMasking.py
* Update to support afw.cameraGeom changes.
* Fix ReadoutCorner usage.
=> DM-18610: Add fields, limited mutability, and trim/assembly-state tracking to cameraGeom

python/lsst/ip/isr/isrTask.py
This should resolve KeyError exceptions when the inputs hash does not
contain defects.
=> DM-22108: Fix gen3 handling of defects.

python/lsst/ip/isr/isrTask.py
Set doSuspect=False by default.
=> DM-22191: isr for yaml cameras is broken due to zero value for suspectLevel

python/lsst/ip/isr/isrMock.py
Pass arguments to CameraWrapper correctly.
This changeset reproduces the current unit test values, while ensuring that the camera is generated correctly.
=> DM-22647: Fix ip_isr.isrMock bug with CameraWrapper() args.

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py
Remove unused config option for specifying files
=> Fix bitrot for using new style brighter-fatter kernels

python/lsst/ip/isr/isrTask.py
Add dateObs handler for IsrTask.getIsrExposure().
Using a fallback filter via IsrConfig.fallbackFilterName to identify
calibrations in gen2 fails, due to the query not being constrained on
the exposure dateObs.  Add a boolean config option
(IsrConfig.useFallbackDate) to supply the dateObs of the raw data to
the query to resolve this issue.
=> DM-22661: isrTask failed to find master flat due to filter difference

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py
Grow large masks after BF correction.
Large masks should be treated like edges in the mask plane.  To do so,
convolve the important problem masks (those that are interpolated) by
a top-hat the size of the BF kernel, and add pixels to the mask if
they are calculated using a significant fraction of masked pixels.
=> DM-23083: Update large masks for BF convolution issues

python/lsst/ip/isr/isrTask.py
Update isrTask runQuantum for new-style BF correction.  This requires examining the object returned from the butler and reworking it to match the expectation of IsrTask().run().
=> DM-22776: Update Gen3 isrTask for BF corrections

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/linearize.py, tests/test_isrMisc.py, tests/test_linearizeLookupTable.py, tests/test_linearizeSquared.py
Implement RFC-665 changes:
* allow linearity to be persisted in a yaml file (giving linearity measurement code a target).
* allow cameraGeom linearity to be overridden.
* pull all duplicated code into a single Linearizer() class.
* demote the current linearize functors to operate on an image view
* Define LinearityType=Proportional as a no-op, and add generic polynomial correction code.
=> DM-23023: Simplify linearity corrections

python/lsst/ip/isr/isrTask.py
Switch gen3 'raw' connection to Input.
This changes the connection from a PrerequisiteInput, allowing raw
datasets to be processed even if unconstrained by a --data-query
argument.  This also removes the constraint that prevents processing
of partial repositories that do not include the full set of
CartesianProduct(registry.exposure, registry.detector).
=> DM-23702: IsrTask should use regular Input for raw data

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/overscan.py, tests/test_empiricalVariance.py, tests/test_isrFunctions.py, tests/test_isrTask.py, tests/test_overscanCorrection.py
Split isrFunctions.overscanCorrection to new class.
This split is necessary to reduce the confusion in overscanCorrection,
reduce the duplication, and limit the number of nested if/else
statements used.  The functionality should be identical, just in
better named and more reusable components.
=> DM-23396: Function "overscanCorrection" in "isrFunctions.py" needs refactoring

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/calibType.py, tests/test_calibType.py
Add IsrCalib and IsrProvenance classes.
IsrCalib should be the base class used by calibration data.
IsrProvenance supplies a concrete example subclass that will allow
calibrations to store their inputs in a way that can be used to
reconstruct the calibration.
=> DM-24537: Add Isr calibration base class

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrMock.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/measureCrosstalk.py, tests/test_crosstalk.py
Implement CrosstalkCalib class inheriting from IsrCalib. 
Add inter-chip crosstalk handling.
Switch to Exposure (no F) as the output product in gen3 to allow IsrTask to process an input in multiple passes.
=> DM-23983: Cannot apply crosstalk in Gen 3 DECam processing

python/lsst/ip/isr/isrTask.py, tests/test_isrTask.py
Add level at which to do Edge masking.
=> DM-26217: Edge masking in IsrTask needs a "level" option to mask detector edges or amplifier edges.

python/lsst/ip/isr/isrTask.py
Add option to reverse Bias and Overscan correction ordering.
=> DM-26316: Allow bias generation to retain overscan signal

python/lsst/ip/isr/overscan.py, tests/test_overscanCorrection.py
Avoid unnecessary warnings in overscan.
Remove masked points to avoid the afwMath.makeStatistics() warning
that occurs with those points.
Add unit test to ensure outlier masking functions correctly.
=> DM-26414: Handle masked pixels in ip_isr's MEDIAN_PER_ROW

python/lsst/ip/isr/fringe.py
Use the same filter name determination in all places that the fringe is checked.
Add fringe support for matching against filter name aliases.
=> DM-26452: Fix fringe filter inconsistency

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/linearize.py
This makes the linearity dataset a subclass of IsrCalib, which hopefully gives better code reuse and consistency between datasets.
=> DM-24703: Make linearity a subclass of lsst.ip.isr.IsrCalib

python/lsst/ip/isr/isrTask.py
The removal of `()` from the See Also sections is a critical fix to support Sphinx 3 builds.
The removal of the `"""!`-style docstring prefix is less critical but makes sense because there's no need for Doxygen support in these docstrings.
=> DM-26826: IsrTask docstring fixes

python/lsst/ip/isr/calibType.py
Handle multi-extension tables correctly.
=> DM-26946: readFits in calibType.ptc seems to fail to read more than one table

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/overscan.py
This issue is a result of an overscan bug when `MEDIAN_BY_ROW` is active and an overscan row is completely masked.  In addition, the DM-26281 overscan debug rework is added here, as it was necessary to diagnose the issue.
=> DM-27157: constructDark.py fails on LSSTCam with 'Image contains no Pixels'

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/linearize.py, tests/test_calibType.py
This changeset adds the spline linearizer, and some additional metadata handling tools to try and enforce more uniform calibration headers.
=> DM-26545: Add spline linearizer.

python/lsst/ip/isr/isrTask.py
Fix handling of saturation interpolation.
doSaturationInterpolation now fully disables saturation interpolation,
even if doSaturation is set to True.  This also now uses the
saturatedMaskName field, as that could cause inconsistency as well.
Fix a related typo.
=> DM-27319: Examine behavior of IsrTask wrt doSaturation and doSaturationInterpolation

python/lsst/ip/isr/isrTask.py
It was also necessary to report statistics after overscan correction to compare with eoTest. This ticket implements the changes to do that reporting in the metadata.
=> DM-26484: Run read noise eotest task at NCSA

python/lsst/ip/isr/fringe.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/straylight.py, tests/test_fringes.py
This ticket also provides a `checkFilter` function, to reduce code duplication between fringe, straylight, etc filter checks against config parameters.
=> DM-28093: Change isrTask (and relevant configs) to use physicalLabel

python/lsst/ip/isr/defects.py
Do not normalize an empty Defects() object.
=> Defects instantiation creates undefined/infinite bbox

python/lsst/ip/isr/brighterFatterKernel.py, python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/ptcDataset.py, tests/test_crosstalk.py
This fixes the missing tests, and enhances the base class __eq__ to reduce code duplication.
=> DM-27103: Not all IsrCalib tests round trip calibrations

python/lsst/ip/isr/isrTask.py
Fix gen2 handling of detector level BF kernels.
=> DM-30738: Backport gen3 imSim BF-kernels for gen2

python/lsst/ip/isr/isrTask.py
Prerequisite inputs are now required by default, and checked during QG generation, since that's what we want for the vast majority of them.
=> DM-30649: Mark optional prerequisite inputs as such.

python/lsst/ip/isr/isrTask.py
=> DM-17471: Save intermediate data product with pre-interpolation pixel values

python/lsst/ip/isr/defects.py
=> DM-31174: str() method failure on lsst.ip.isr.Defects class

python/lsst/ip/isr/isrTask.py, tests/test_empiricalVariance.py, tests/test_isrTask.py
Add options to mask pixels with negative variance by default.  This should never happen on science images, so this should be a safe change.
Add a test to check this, but let it be disabled in most of the IsrTask tests, as those operate on mock images that are not necessarily constructed the same way a science image is.
=> DM-31394: Overscan subtraction can create negative variance

python/lsst/ip/isr/ampOffset.py, python/lsst/ip/isr/isrTask.py
This commit adds a placeholder amp offset task which is not implemented
here, and instead should be retargeted by a camera specific version.
=> DM-24389: Implement amp-to-amp offset correction task

python/lsst/ip/isr/brighterFatterKernel.py, python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/linearize.py, tests/test_linearize.py, tests/test_linearizeLookupTable.py, tests/test_linearizeSquared.py
Python logging now preferred for all python code so change IsrCalib to create a python logger.
=> DM-31696: Switch to python logging

python/lsst/ip/isr/calibType.py, tests/test_calibType.py
Allow generic readFits/readText usage for IsrCalib.
IsrCalib has previously relied on subclasses implementing fromDict and
fromTable methods, calling the inherited readText and readFits
methods.  However, adding the calibration class to the metadata by
default (added during calls to updateMetadata) allows the base class
to be used for generic reads, eliminating the need to add
storageClasses/formatters.
=> DM-29531: Update IsrCalib so it can serve as StorageClass for subclasses

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/photodiode.py, tests/test_photodiode.py
Add photodiode calibration class.
=> DM-30648: Add photodiode calibration class

python/lsst/ip/isr/isrTask.py
This PR removes uses of `VisitInfo.getExposureId()`, which was deprecated in lsst/afw#614.
=> DM-13943: Deprecate VisitInfo.getExposureId()

python/lsst/ip/isr/isrTask.py
`metadata.set(a, b)` is the same as `metadata[a] = b` and the latter can work for more general types of metadata objects.
=> DM-32682: Use standard python syntax for setting metadata

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/vignette.py, tests/test_isrMisc.py, tests/test_isrTask.py, tests/test_setValidPolygonIntersect.py
Logic changed, and masking function updated so it can be used generically.
=> DM-29326: Fix logic of the doVignette option in isrTask

python/lsst/ip/isr/overscan.py
Identify spline fit problems, work around them, but mask the amplifier.
=> DM-33530: Spline fitter fails when insufficient length array input

python/lsst/ip/isr/vignette.py
Return if no polygon is supplied.
=> DM-34407: cp_pipe flat construction fails due to missing vignette polygon

python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, tests/test_fringes.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
=> DM-27177: Deprecate transitional getFilterLabel API

python/lsst/ip/isr/brighterFatterKernel.py
Fix brighter-fatter kernel backwards compatibility.
This fixes the translation between the FITS table and the intermediate dictionary representation.
=> DM-35349: Fix brighter fatter kernel backwards compatibility

python/lsst/ip/isr/ptcDataset.py
Check array length before attempting to access entry -1.
=> DM-35594: Fully masked amplifiers can trigger read failures for PTC

doc/doxygen.conf.in, include/lsst/ip/isr/isr.h, python/lsst/ip/isr/assembleCcdTask.py
This PR removes or rearranges Doxygen comments that were intended to be file-level (or, in one case, block-level) but instead described namespaces, and also fixes some Doxygen warnings discovered during testing.
=> DM-22823: Remove accidental Doxygen comments for namespaces

python/lsst/ip/isr/isrStatistics.py
Fix errors in creating CTI statistics.
=> DM-35821: Fix CTI run errors

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/overscan.py, tests/test_isrFunctions.py, tests/test_isrTask.py, tests/test_overscanCorrection.py
* Remove isrFunction intermediate for overscan correction.
* Add support for parallel overscan correction.
* Fix handling of column/row skipping, to ensure that overscan result is subtracted where needed.
* Consolidate unit tests for overscan correction in one location.
=> DM-33429: Add ability to do both serial and parallel overscan correction

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py, tests/test_isrFunctions.py
Move countMaskedPixels from cp_pipe, and use it to check that the amplifier is fully masked.
=> DM-35569: ip_isr doEmpiricalReadNoise fails if an amplifier is fully masked

python/lsst/ip/isr/brighterFatterKernel.py
Repack correlations if needed to ensure consistent lengths.
=> DM-36337: Brighter-fatter kernels cannot be converted for disk due to length error

python/lsst/ip/isr/overscan.py
Add parallel overscan results to the task output.
=> DM-36653: Ensure overscan task returns all overscan models and images

python/lsst/ip/isr/overscan.py
Fix parallelOverscan bleed mask threshold.
=> DM-37022: overscan.py parallel overscan sigma clip is really a threshold clip

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/overscan.py
Add image quality values to image header.
=> DM-37205: Confirm quantities needed for image quality analysis from ISR are in postIsrCcd

python/lsst/ip/isr/isrTask.py
Fix case where a metadata entry may not exist.
=> DM-37393: Fix missing key when overscan fails

python/lsst/ip/isr/isrStatistics.py, tests/test_isrStatistics.py
Add banding metrics, full amplifier projection extraction, and projection FFTs.
=> DM-36994: Add additional metrics to ip_isr

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/overscan.py, tests/test_overscanCorrection.py
This update switches from a fractional-based masking that turns the parallel overscan correction on and off to a fixed threshold based mask that attempts to patch the fully masked columns from unmasked columns.  The mask generated from the threshold is applied across all amplifiers, to ensure crosstalk ghosts of the original bright bleed are also excluded from the calculations.
=> DM-37357: Update masking in parallel overscan

tests/test_overscanCorrection.py
Use assertAlmostEqual to avoid potential floating point differences.
=> DM-37806: DM-37357 broke ip_isr tests on macOS

python/lsst/ip/isr/isrTask.py, tests/test_isrTask.py
=> DM-38044: Logging error in isrTask

python/lsst/ip/isr/ptcDataset.py
Fix error that allowed duplicate PTC ampNames.
=> DM-38163: Update PTC to avoid potential failures

python/lsst/ip/isr/linearize.py, tests/test_linearize.py, tests/test_linearizeLookupTable.py
Fix spline linearity-induced amplifier offsets.
=> DM-38777: LinearizeSpline linearity corrections do not anchor the spline at zero flux

python/lsst/ip/isr/overscan.py
Pass only data to np.percentile from overscan maskedArray.
=> DM-38973: Call to np.percentile in overscan.py leads to numpy warnings with 1.23

python/lsst/ip/isr/photodiode.py
This will be used for TS8 and LSSTCam data taken at SLAC for Run 6 testing.
=> DM-39140: add photodiode integration algorithm for use with CCOB

python/lsst/ip/isr/photodiode.py, tests/test_photodiode.py
Flatten arrays, and remove 2d indexing in integrateChargeSum.
Add unit tests for array shape, and for integrateChargeSum return values.
=> DM-39338: flatten arrays in photodiode calibration

python/lsst/ip/isr/deferredCharge.py
Modern numpy requires a size be picked.
=> DM-39726: Use float64 rather than generic float type

python/lsst/ip/isr/defects.py
Allocating the MaskedImage thousands of times uses a lot of resources. Allocating a Mask is much quicker.
=> DM-39613: Use Mask for normalization rather than MaskedImage

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrTask.py
I've also folded in the change from youtsumi:u/youtsumi/DM-40049 to fix the max iteration log message.
=> DM-40094  Convolution control edge copy method results in diverging correction in fluxConservingBrighterFatterCorrection

python/lsst/ip/isr/isrTask.py
Simplify header provenance code and fix BF errors:
* Move calibration date searches to runQuantum with the rest of the header provenance.
* Handle inputs that change name during the header provenance (only brighter-fatter kernels currently).
* Retain header validation checks in the run method.
=> DM-40128: Fix brighter-fatter loading errors

python/lsst/ip/isr/isrTaskLSST.py
Here is a first draft of the new isr task implementing calibpalooza ISR steps order.
The new task is called isrTaskLSST.
Note that there are a lot of things missing: upstream changes to the ISR task, few docstring, unit test, further testing. These will be in follow-up tickets.
Note also that we are focusing on LSSTCam and not trying to have HSC and DECam use this task. Can be done if needed in follow-up tickets.  
Also, I ran into git issues multiple times so I ended up re-commiting the isrTaskLSST file in big chunks in only a few commits.
=> DM-36647: First draft of new isr task 

python/lsst/ip/isr/deferredCharge.py, python/lsst/ip/isr/isrStatistics.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/isrTaskLSST.py, tests/test_deferredCharge.py
Enforce gain usage in CTI construction and application.
=> DM-41754: Check handling of gains in CTI code.

python/lsst/ip/isr/__init__.py, python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrStatistics.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/isrTaskLSST.py, python/lsst/ip/isr/overscan.py, python/lsst/ip/isr/overscanAmpConfig.py, tests/test_overscanAmpConfig.py, tests/test_overscanCorrection.py
This also adds crosstalk correction in the parallel overscan region.
=> DM-41316: Refactor overscan task for IsrTaskLSST into serial/parallel tasks.

python/lsst/ip/isr/isrStatistics.py, python/lsst/ip/isr/isrTask.py
Add method to copy calibration statistics to isrStatistics.
=> DM-42160:  eo_pipe/cp_verify parity: dark

python/lsst/ip/isr/fringe.py
This PR fixes a log that was printed using `print` instead of `debug` (added on #116). It is the only non-UI `print` statement in the package code.
=> DM-42708: Avoid printing debug logs directly to stdout

python/lsst/ip/isr/ptcDataset.py
Remove incorrect NOISE_LIST access.
As this is a newly added field, it should only be set in a version controlled block.  This ticket removes the extra assignment.
=> DM-42795: Fix incorrect NOISE_LIST access.

doc/lsst.ip.isr/index.rst, doc/lsst.ip.isr/tasks/lsst.ip.isr.assembleCcdTask.AssembleCcdTask.rst, python/lsst/ip/isr/ampOffset.py, python/lsst/ip/isr/assembleCcdTask.py, python/lsst/ip/isr/isrStatistics.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/ptcDataset.py
This PR demotes a `warning` log issued when constructing a linearizer (something the task is specifically configured to do) to `info`. It also fixes numerous documentation errors in both Doxygen and Sphinx, in part by migrating `AssembleCcdTask` to the task topic format.
=> DM-42999: Demote routine "warnings" and fix build problems

python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/isrTaskLSST.py
Ensure defects are passes to the IsrStatisticsTask so header keywords can be saved.
=> DM-42927: Update cp_verify connections/classes/outputs for analysis_tools

python/lsst/ip/isr/isrTask.py
Binned images should be exposures.
=> DM-41442: Add focal plane mosaic construction to cp_pipe/cp_verify

python/lsst/ip/isr/overscan.py, tests/test_overscanCorrection.py
This PR also removes some vestigial code that was not used or tested (from before we implemented the C++ row-by-row MEDIANs).
=> DM-45151: Fix use of overscanIsInt and add appropriate tests.

python/lsst/ip/isr/calibType.py, python/lsst/ip/isr/ptcDataset.py, tests/test_ptcDataset.py
As discovered in development of DM-45856 the PTC dataset can be improved (now version 2.0 because that is the number after 1.9, not for any semantic versioning reasons).
* We should have the `gainList` to go with the `noiseList` which tracks the gain from flat pairs in the combined PTC
* We can now store string-based auxiliary metadata, including observation reason and science program.
* The PTC `sort` and `appendPartialPtc` methods are added so that the PTC solver in `cp_pipe` doesn't need to monkey with internals (and risk missing appending/sorting a field)
* A comment has been added to explicitly list which functions should be updated when a new field is added with a new PTC version.
=> DM-46308: Update PTC dataset to 2.0 and add more fields and methods.

python/lsst/ip/isr/crosstalk.py, python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrMockLSST.py, python/lsst/ip/isr/isrTask.py, python/lsst/ip/isr/isrTaskLSST.py, python/lsst/ip/isr/linearize.py, python/lsst/ip/isr/overscan.py, python/lsst/ip/isr/overscanAmpConfig.py, python/lsst/ip/isr/vignette.py, tests/test_isrMisc.py, tests/test_isrTaskLSST.py, tests/test_overscanCorrection.py
This PR contains a number of updates to ip_isr based on testing of the new task and pipelines from DM-45856.  Aside from bug fixes and checks of invalid (nan) crosstalk matrix values, there are a large number of updates to the parallel overscan masking to ensure that (a) saturated flats don't get oversubtracted; (b) saturated and unsaturated defect bleeds into the parallel overscan region are handled correctly.
This also takes advantage of crosstalk `fitGains` to apply reasonable gain values when applying crosstalk corrections to bootstrap frames.
=> DM-46052: Updates to IsrTaskLSST based on testing on real LATISS and LSSTCam images.

python/lsst/ip/isr/isrFunctions.py, python/lsst/ip/isr/isrMockLSST.py, python/lsst/ip/isr/isrTaskLSST.py, tests/test_isrTaskLSST.py
This also adds appropriate tests that the calibration variance planes are being used.
=> DM-48251: Add bias and dark variance planes to IsrTaskLSST variance plane.

python/lsst/ip/isr/isrTaskLSST.py
=> DM-35396: Add calib date to dataset provenance

python/lsst/ip/isr/isrTask.py
I've demoted the message in this case to debug, so it can be caught if needed.
This doesn't trigger in `ci_cpp_gen3`, because this is only called in the old `IsrTask` code (`ci_cpp_gen3` has switched to the LSST specific version).
=> DM-11270: Please don't warn about zero points for exposure times of 0

python/lsst/ip/isr/isrTaskLSST.py
Note that this also ensures that this mask plane is always added.
=> DM-48964: Turn on UNMASKEDNAN interpolation by default in IsrTaskLSST

python/lsst/ip/isr/isrTaskLSST.py
This PR fixes a presumed copy-paste error in the docs for `bssVoltageMinimum`.
=> DM-50625: ComCamSim can't pass minimum voltage check
